### ISSUE TITLE
Installing freeCAD

### ISSUE THREAD

**Issue by devangcx** [ENAC-CNPA/BIMxBEM#1]
Hi @CyrilWaechter,

I have looked at various articles and I am not sure how to install freecad as a package that I can use with Python. Can you help?

I am trying to accomplish [this](https://pythoncvc.net/?p=839). I read the comments on one of your posts where I see that people have tried installing freecad. I could not follow it.

**Comment by CyrilWaechter** [comment]
Hello @devngc 

On what OS are you ?
You can simply download and install FreeCAD from [download page](https://www.freecadweb.org/downloads.php?lang=fr) or get it from your distro package manager if you are on GNU/Linux.

If FreeCAD is packaged with python (like on Windows for example) you need to use the python packaged with FreeCAD or at least the same version.

**Comment by devangcx** [comment]
I am on Windows and would like to use it with Python installed on my system. 

> If FreeCAD is packaged with python (like on Windows for example) you need to use the python packaged with FreeCAD or at least the same version.

I am not sure if we get FreeCAD as a package with python. Can you elaborate more on this? This is what I am really interested in.

**Comment by CyrilWaechter** [comment]
@devngc by default FreeCAD is packaged with python on windows. You’ll find it in `<FreeCAD folder>\bin\python.exe`
Just install it from last release (previous link or from [github release page](https://github.com/FreeCAD/FreeCAD/releases)).

**Comment by devangcx** [comment]
I think there's a misunderstanding. I am trying to using with Pure python.
![Capture](https://user-images.githubusercontent.com/20086924/132866183-072ca64e-aa97-463c-bb53-0f5b61801767.PNG)

**Comment by devangcx** [comment]
I see the python.exe in the folder that you mentioned. But how do import FreeCAD as a package in pure python? Do I have to add that python.exe in my environment path and use it rather than the already installed python on my system?

**Comment by CyrilWaechter** [comment]
> I see the python.exe in the folder that you mentioned. But how do import FreeCAD as a package in pure python?

Yes :smiley: , `import FreeCAD` and eventually `import FreeCADGui` if wanted as in the article.
I you like we can make a quick screenshare. You can join https://matrix.to/#/#OSArch:matrix.org to chat and eventually screenshare.

**Comment by devangcx** [comment]
Thanks. I have joined element.

**Comment by CyrilWaechter** [comment]
Following our meeting I close this issue. Curious to see what you are going to do.
